<a href="https://colab.research.google.com/github/MaddoSaru/deeplearning-az/blob/master/RNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Deep Learning***

# **Redes Neuronales Artificiales (RNA)**

**Parte 1 - Pre procesado de datos**

In [3]:
# Importar librerías

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Importar el dataset

dataset = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/deeplearning-az/master/datasets/Part%201%20-%20Artificial%20Neural%20Networks%20(ANN)/Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [17]:
# Seleccionar variables dependiente e independientes

X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [18]:
# Tratar datos categóricos

from sklearn.preprocessing import LabelEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1]) # Cambiar variable Geography
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) # Cambiar variable Gender

print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [19]:
# Transformar a variable Dummy

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ("Churn_Modelling",        # Un nombre de la transformación
         OneHotEncoder(categories='auto'), # La clase a la que transformar
         [1]            # Las columnas a transformar.
         )
    ], remainder='passthrough'
)

X = transformer.fit_transform(X)
X = X[:, 1:]

print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [20]:
# Dividir el data set en conjunto de entrenamiento y conjunto de testing

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [21]:
# Escalado de variables

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

**Parte 2 - Construir la RNA**

In [107]:
# Importar Keras y librerías adicionales

import keras
from keras.models import Sequential # Inicializar los parámetros de la RNA
from keras.layers import Dense # Declarar y crear las capas de la RNA
from keras.layers import Dropout

In [108]:
# Inicializar la RNA

classifier = Sequential()

In [109]:
# Añadir la capa de entrada y primera capa oculta

classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
classifier.add(Dropout(rate = 0.1))

In [110]:
# Añadir la segunda capa oculta

classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
classifier.add(Dropout(rate = 0.1))

In [111]:
# Añadir la capa de salida

classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

In [112]:
# Compilar la RNA

classifier.compile(optimizer = "rmsprop", loss = "binary_crossentropy", metrics = ["accuracy"])

In [113]:
# Ajustamos la RNA al Conjunto de Entrenamiento

classifier.fit(X_train, y_train,  batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 982us/step - loss: 0.6264 - accuracy: 0.7937
Epoch 2/100
250/250 [==============================] - 0s 979us/step - loss: 0.4797 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4443 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4374 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 960us/step - loss: 0.4302 - accuracy: 0.7987
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4271 - accuracy: 0.8174
Epoch 7/100
250/250 [==============================] - 0s 970us/step - loss: 0.4229 - accuracy: 0.8198
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8165
Epoch 9/100
250/250 [==============================] - 0s 957us/step - loss: 0.4162 - accuracy: 0.8227
Epoch 10/100
250/250 [==============================] - 0s 986us/step - loss: 0.4

**Parte 3 - Evaluar el modelo y calcular predicciones finales**

In [114]:
# Predicción de los resultados con el Conjunto de Testing

y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

In [115]:
# Elaborar una matriz de confusión

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)
print("Accuracy: ",(cm[0][0]+cm[1][1])/cm.sum())

[[1525   70]
 [ 198  207]]
Accuracy:  0.866


**Tarea 1 - ¿Deberíamos despedirnos de ese cliente?**

In [64]:
# Crear el nuevo cliente

cliente = np.array([[0,0,600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [65]:
# Escalado de la nueva variable

sc_X = StandardScaler()
cliente = sc_X.fit_transform(cliente)
prediccion = classifier.predict(cliente)
prediccion = (prediccion > 0.5)

print(prediccion)

[[False]]


In [66]:
# Matriz de confusión

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print((cm[0][0]+cm[1][1])/cm.sum())

0.838


**Parte 4 - Evaluar, mejorar y ajustar la RNA**

In [67]:
### Evaluar la **RNA**

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform", activation = "sigmoid"))
  classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator=classifier, X = X_train, y = y_train, cv = 10, n_jobs=-1, verbose = 1)

mean = accuracies.mean()
variance = accuracies.std()

print("La media es: ", mean)
print("La varianza es: ", variance)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


La media es:  0.7960000097751617
La varianza es:  0.010105690527913859


[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:   13.2s finished


In [106]:
### Mejorar la RNA
#### Regularización de Dropout para evitar el *overfitting*

### Ajustar la *RNA*
from sklearn.model_selection import GridSearchCV # sklearn.grid_search

def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))
  classifier.compile(optimizer = optimizer, loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size' : [16,25,32],
    'nb_epoch' : [50,100,250,500], 
    'optimizer' : ['adam', 'rmsprop']
}

grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters, 
                           scoring = 'accuracy', 
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

print(best_parameters)
print(best_accuracy)

500/500 [==============================] - 1s 1ms/step - loss: 0.5093 - accuracy: 0.7949
{'batch_size': 16, 'nb_epoch': 50, 'optimizer': 'adam'}
0.796
